Models/BarcodeResultViewModel.cs
namespace BarcodeTest.Models
{
    [Serializable]
    public class BarcodeResultViewModel
    {
        public int ResponseCode { get; set; }
        public string Text { get; set; } = string.Empty;
        public string Format { get; set; } = string.Empty;
        public string TimeElapse { get; set; } = string.Empty;
    }
}

Models/ErrorViewModel.cs
namespace BarcodeTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using BarcodeTest.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using IronBarCode;
using System.Drawing;

namespace BarcodeTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        static readonly Stopwatch timer = new Stopwatch();
        static readonly Stopwatch timer2 = new Stopwatch();

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Index(string image)
        {
            Console.WriteLine("Inicio de Script");
            timer2.Restart();
            BarcodeResultViewModel model = new();

            var imgBytes = Convert.FromBase64String(image);

            BarcodeReaderOptions options = new BarcodeReaderOptions()
            {
                Speed = ReadingSpeed.ExtremeDetail,
                ExpectBarcodeTypes = BarcodeEncoding.EAN13 | BarcodeEncoding.EAN8 | BarcodeEncoding.UPCA | BarcodeEncoding.UPCE | BarcodeEncoding.PharmaCode
            };

            timer.Restart();

            BarcodeResults Results = BarcodeReader.Read(imgBytes, options);

            timer.Stop();

            if (Results.Any())
            {
                BarcodeResult Result = Results.First();

                Console.WriteLine("Codigo: " + Result.Text);
                Console.WriteLine("Formato: " + Result.BarcodeType);
                Console.WriteLine("Tiempo en Decodificar: " + timer.Elapsed);

                model.ResponseCode = 0;
                model.Text = Result.Text;
                model.Format = Result.BarcodeType.ToString();
                model.TimeElapse = timer.Elapsed.ToString();

                timer2.Stop();
                Console.WriteLine("Tiempo en ejecutar script: " + timer2.Elapsed);

                return Json(model);
            }
            else
            {
                Console.WriteLine("No se encontro nigun codigo de barras");

                model.ResponseCode = 1;

                timer2.Stop();
                Console.WriteLine("Tiempo en ejecutar script: " + timer2.Elapsed);

                return Json(model);
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WebCamController.cs
using BarcodeTest.Models;
using IronBarCode;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Drawing;

namespace BarcodeTest.Controllers
{
    public class WebCamController : Controller
    {
        static readonly Stopwatch timer = new Stopwatch();
        public WebCamController()
        {
            
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CaptureImage(string name)
        {
            try
            {
                BarcodeResultViewModel model = new();
                var files = HttpContext.Request.Form.Files;

                if (files != null)
                {
                    foreach (var file in files)
                    {
                        if (file.Length > 0)
                        {
                            using (var Stream = new MemoryStream())
                            {
                                file.CopyTo(Stream);
                                using (var img = Image.FromStream(Stream))
                                {
                                    timer.Restart();
                                    timer.Start();

                                    BarcodeResults Results = BarcodeReader.Read(img);

                                    timer.Stop();

                                    if (Results.Any())
                                    {
                                        BarcodeResult Result = Results.First();

                                        Console.WriteLine("Codigo: " + Result.Text);
                                        Console.WriteLine("Formato: " + Result.BarcodeType);

                                        model.ResponseCode = 0;
                                        model.Text = Result.Text;
                                        model.Format = Result.BarcodeType.ToString();
                                        model.TimeElapse = timer.Elapsed.ToString();

                                        return Json(model);
                                    }
                                    else
                                    {
                                        Console.WriteLine("No se encontro nigun codigo de barras");

                                        model.ResponseCode = 1;

                                        return Json(model);
                                    }
                                }
                            }
                        }
                    }
                    model.ResponseCode = 2;
                    return Json(model);
                }
                else
                {
                    model.ResponseCode = 2;
                    return Json(model);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
video {
    max-width: 100%;
}

.decode-controls {
    position: absolute;
    bottom: 20px;
    left: 50%;
    transform: translateX(-50%);
}

.decode-controls > button {
    transform: scale(1.5);
}

canvas {
    position: fixed;
    top:0;
    left: 0;
    opacity: 0;
    z-index: -9999;
}
</style>

    <p>Codigo: <b id="codigo"></b></p>
    <p>Formato: <b id="formato"></b></p>
    <p>Decodificado en: <b id="tiempo"></b></p>

    <div class="camara-controls">
        <button onclick="stopCamera()" class="btn btn-secondary">Detener Camara</button>
    </div>

    <div class="decode-controls">
        <button onclick="capture()" id="scan" class="btn btn-primary">Escanear</button>
    </div>

    <video autoplay id="camara"></video>
    <canvas id="canvas"></canvas>

<script src="~/js/test.js"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarcodeTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BarcodeTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BarcodeTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebCam" asp-action="Index">Webcam Version</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/WebCam/CaptureImage.cshtml
<body class="container">
    <div class="row">
        <div class="col-md-6" style="padding-top:50px;">
            <div class="panel panel-default">
                <div class="panel-heading">Live Web Camera</div>
                <div class="panel-body">
                    <div id="LiveCamera" style="margin-bottom:50px;"></div>
                    <form>
                        <input type="button" class="btn btn-primary" value="Capture Snapshot" onClick="CaptureSnapshot()">
                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding-top:50px;">
            <div class="panel panel-default">
                <div class="panel-heading">Captured Snapshot/Image</div>
                <div class="panel-body">
                    <div id="results">Your snapshot will appear here...</div>
                    <p>Codigo: <b id="codigo"></b></p>
                    <p>Formato: <b id="formato"></b></p>
                    <p>Decodificado en: <b id="tiempo"></b></p>
                </div>
                <br />
                <br />
            </div>
        </div>
    </div>
    

    <!-- Include the Webcam.js JavaScript Library -->
    <script src="~/webcamjs/webcam.js"></script>
    <script src="~/js/jpeg_camera_with_dependencies.min.js"></script>
    <!-- Configure web cam settings -->
    <script language="JavaScript">
        Webcam.set({
            width: 500,
            height: 375,
            image_format: 'png',
            jpeg_quality: 100
        });

        Webcam.attach('#LiveCamera');
    </script>

    <!-- Javascript code to capture the snapshot and displaying it in the screen -->
    <script language="JavaScript">
        function CaptureSnapshot() {
            Webcam.snap(function (data) {
                // display results in page
                document.getElementById('results').innerHTML = '<img src="' + data + '"/>';
                // Loading message
                document.getElementById('codigo').textContent = "Decodificando..."
                document.getElementById('formato').textContent = ""
                document.getElementById('tiempo').textContent = ""
                // Send image data to the controller
                Webcam.upload(data,
                    '/WebCam/CaptureImage',
                    function (code, response) {
                        if (code == 200) {
                            response = JSON.parse(response)
                            console.log(response)
                            if (response.responseCode == 0) {
                                document.getElementById('codigo').textContent = response.text
                                document.getElementById('formato').textContent = response.format
                                document.getElementById('tiempo').textContent = response.timeElapse
                            } else if (response.responseCode == 1) {
                                document.getElementById('codigo').textContent = "No se encontro ningun codigo de barras"
                                document.getElementById('formato').textContent = ""
                                document.getElementById('tiempo').textContent = ""
                            } else {
                                alert("Ha ocurrido un error inesperado")
                            }
                        }
                    }
                );
            });
        }
    </script>
</body>

Views/WebCam/Index.cshtml
<body class="container">
    <div class="row">
        <div class="col-md-6" style="padding-top:50px;">
            <div class="panel panel-default">
                <div class="panel-heading">Live Web Camera</div>
                <div class="panel-body">
                    <div id="LiveCamera" style="margin-bottom:50px;"></div>
                    <form>
                        <input type="button" class="btn btn-primary" value="Capture Snapshot" onClick="CaptureSnapshot()">
                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding-top:50px;">
            <div class="panel panel-default">
                <div class="panel-heading">Captured Snapshot/Image</div>
                <div class="panel-body">
                    <div id="results">Your snapshot will appear here...</div>
                    <p>Codigo: <b id="codigo"></b></p>
                    <p>Formato: <b id="formato"></b></p>
                    <p>Decodificado en: <b id="tiempo"></b></p>
                </div>
                <br />
                <br />
            </div>
        </div>
    </div>
    

    <!-- Include the Webcam.js JavaScript Library -->
    <script src="~/webcamjs/webcam.js"></script>
    <script src="~/js/jpeg_camera_with_dependencies.min.js"></script>
    <!-- Configure web cam settings -->
    <script language="JavaScript">
        Webcam.set({
            width: 500,
            height: 375,
            image_format: 'png',
            jpeg_quality: 100
        });

        Webcam.attach('#LiveCamera');
    </script>

    <!-- Javascript code to capture the snapshot and displaying it in the screen -->
    <script language="JavaScript">
        function CaptureSnapshot() {
            Webcam.snap(function (data) {
                // display results in page
                document.getElementById('results').innerHTML = '<img src="' + data + '"/>';
                // Loading message
                document.getElementById('codigo').textContent = "Decodificando..."
                document.getElementById('formato').textContent = ""
                document.getElementById('tiempo').textContent = ""
                // Send image data to the controller
                Webcam.upload(data,
                    '/WebCam/CaptureImage',
                    function (code, response) {
                        if (code == 200) {
                            response = JSON.parse(response)
                            console.log(response)
                            if (response.responseCode == 0) {
                                document.getElementById('codigo').textContent = response.text
                                document.getElementById('formato').textContent = response.format
                                document.getElementById('tiempo').textContent = response.timeElapse
                            } else if (response.responseCode == 1) {
                                document.getElementById('codigo').textContent = "No se encontro ningun codigo de barras"
                                document.getElementById('formato').textContent = ""
                                document.getElementById('tiempo').textContent = ""
                            } else {
                                alert("Ha ocurrido un error inesperado")
                            }
                        }
                    }
                );
            });
        }
    </script>
</body>